const fs = require('fs');
const content = fs.readFileSync('./src/modules/doctor/doctor-components/login/DoctorSignupForm.jsx', 'utf8');
const lines = content.split('\n');

const newLines = [
  ...lines.slice(0, 218),
  '                              type="tel"',
  '                              value={doctorSignupData.phone}',
  '                              onChange={handleDoctorSignupChange}',
  '                              autoComplete="tel"',
  '                              required',
  '                              placeholder="9876543210"',
  '                              maxLength={10}',
  '                              inputMode="numeric"',
  '                              className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 pl-11 text-sm text-slate-900 shadow-sm outline-none transition focus:border-[#11496c] focus:outline-none focus:ring-2 focus:ring-[#11496c]/20"',
  '                              style={{ \'--tw-ring-color\': \'rgba(17, 73, 108, 0.2)\' }}',
  '                            />',
  '                          </div>',
  '                        </div>',
  '                      </section>',
  '                    </motion.div>',
  '                  )}',
  '',
  '                  {/* Step 2: Professional Information */}',
  '                  {signupStep === 2 && (',
  '                    <motion.div',
  '                      initial={{ opacity: 0, x: 20 }}',
  '                      animate={{ opacity: 1, x: 0 }}',
  '                      exit={{ opacity: 0, x: -20 }}',
  '                      className="space-y-5"',
  '                    >',
  '                      <div className="mb-6 pb-4 border-b border-slate-200">',
  '                        <h3 className="text-xl font-bold text-slate-900 mb-1">Professional Information</h3>',
  '                        <p className="text-xs text-slate-500">Tell us about your professional background</p>',
  '                      </div>',
  '                      <section className="grid gap-3 sm:gap-4 sm:grid-cols-2">',
  '                        <div className="flex flex-col gap-1.5 sm:col-span-2">',
  '                          <label htmlFor="category" className="text-sm font-semibold text-slate-700">',
  '                            Category <span className="text-red-500">*</span>',
  '                          </label>',
  '                          <div className="relative">',
  '                            <span className="absolute inset-y-0 left-3 flex items-center text-[#11496c] z-10">',
  '                              <IoMedicalOutline className="h-5 w-5" aria-hidden="true" />',
  '                            </span>',
  '                            <select',
  '                              id="category"',
  '                              name="category"',
  '                              value={doctorSignupData.category}',
  '                              onChange={handleDoctorSignupChange}',
  '                              required',
  '                              className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 pl-11 text-sm text-slate-900 shadow-sm outline-none transition focus:border-[#11496c] focus:outline-none focus:ring-2 focus:ring-[#11496c]/20"',
  '                              style={{ \'--tw-ring-color\': \'rgba(17, 73, 108, 0.2)\' }}',
  '                            >',
  '                              <option value="">Select a category</option>',
  '                              {categories.map((cat) => (',
  '                                <option key={cat._id} value={cat._id}>{cat.name}</option>',
  '                              ))}',
  '                            </select>',
  '                          </div>',
  '                        </div>',
  '',
  '                        <div className="flex flex-col gap-1.5 sm:col-span-2">',
  '                          <label htmlFor="subcategories" className="text-sm font-semibold text-slate-700">',
  '                            Symptoms / Subcategories <span className="text-red-500">*</span>',
  '                          </label>',
  '                          <div className="flex flex-wrap gap-2 mb-2">',
  '                            {(doctorSignupData.subcategories || []).map((subVal, index) => (',
  '                              <span',
  '                                key={index}',
  '                                className="inline-flex items-center gap-1 rounded-full bg-[#11496c] px-3 py-1 text-xs font-semibold text-white"',
  '                              >',
  '                                {getSubcategoryName(subVal)}',
  '                                <button',
  '                                  type="button"',
  '                                  onClick={() => removeSubcategory(subVal)}',
  '                                  className="hover:text-slate-200"',
  '                                >',
  '                                  ×',
  '                                </button>',
  '                              </span>',
  '                            ))}',
  '                          </div>',
  '                          <div className="relative">',
  '                            <span className="absolute inset-y-0 left-3 flex items-center text-[#11496c] z-10">',
  '                              <IoMedicalOutline className="h-5 w-5" aria-hidden="true" />',
  '                            </span>',
  '                            <input',
  '                              type="text"',
  '                              value={subcategorySearch}',
  '                              onChange={(e) => {',
  '                                setSubcategorySearch(e.target.value);',
  '                                setShowSubcategoryDropdown(true);',
  '                              }}',
  '                              onFocus={() => setShowSubcategoryDropdown(true)}',
  '                              onKeyDown={(e) => {',
  '                                if (e.key === \'Enter\' && showSubcategoryDropdown) {',
  '                                  e.preventDefault();',
  '                                  if (filteredSubcategories.length > 0) {',
  '                                    handleSubcategorySelect(filteredSubcategories[0]);',
  '                                  } else if (subcategorySearch.trim()) {',
  '                                    handleCustomSubcategoryAdd();',
  '                                  }',
  '                                } else if (e.key === \'Escape\') {',
  '                                  setShowSubcategoryDropdown(false);',
  '                                }',
  '                              }}',
  '                              placeholder={doctorSignupData.category ? "Type to search symptoms..." : "Please select a category first"}',
  '                              disabled={!doctorSignupData.category}',
  '                              className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 pl-11 pr-10 text-sm text-slate-900 shadow-sm outline-none transition focus:border-[#11496c] focus:outline-none focus:ring-2 focus:ring-[#11496c]/20 disabled:bg-slate-100 disabled:text-slate-500 disabled:cursor-not-allowed"',
  '                              style={{ \'--tw-ring-color\': \'rgba(17, 73, 108, 0.2)\' }}',
  '                            />',
  '                            {subcategorySearch && (',
  '                              <button',
  '                                type="button"',
  '                                onClick={() => {',
  '                                  setSubcategorySearch(\'\')',
  '                                  setShowSubcategoryDropdown(false)',
  '                                }}',
  '                                className="absolute inset-y-0 right-3 flex items-center text-slate-400 hover:text-slate-600 z-10"',
  '                              >',
  '                                <IoCloseOutline className="h-4 w-4" />',
  '                              </button>',
  '                            )}',
  '                            {showSubcategoryDropdown && doctorSignupData.category && (',
  '                              <div className="absolute z-50 mt-1 w-full max-h-60 overflow-auto rounded-xl border border-slate-200 bg-white shadow-lg">',
  '                                {filteredSubcategories.length > 0 ? (',
  '                                  <div className="py-1">',
  '                                    {filteredSubcategories.map((sub) => (',
  '                                      <button',
  '                                        key={sub._id}',
  '                                        type="button"',
  '                                        onClick={() => handleSubcategorySelect(sub)}',
  '                                        className="w-full px-4 py-2.5 text-left text-sm text-slate-700 hover:bg-[#11496c] hover:text-white transition-colors flex items-center gap-2"',
  '                                      >',
  '                                        <IoMedicalOutline className="h-4 w-4 flex-shrink-0" />',
  '                                        <span>{sub.name}</span>',
  '                                      </button>',
  '                                    ))}',
  '                                  </div>',
  '                                ) : (',
  '                                  <div className="px-4 py-3 text-sm text-slate-500">',
  '                                    No matching symptoms found.',
  '                                  </div>',
  '                                )}',
  '                                {subcategorySearch.trim() && !filteredSubcategories.some(s => s.name.toLowerCase() === subcategorySearch.trim().toLowerCase()) && (',
  '                                    <div className="border-t border-slate-200">',
  '                                      <button',
  '                                        type="button"',
  '                                        onClick={handleCustomSubcategoryAdd}',
  '                                        className="w-full px-4 py-2.5 text-left text-sm text-[#11496c] hover:bg-[#11496c] hover:text-white transition-colors flex items-center gap-2 font-medium"',
  '                                      >',
  '                                        <IoAddOutline className="h-4 w-4 flex-shrink-0" />',
  '                                        <span>Add "{subcategorySearch.trim()}" (Press Enter)</span>',
  '                                      </button>',
  '                                    </div>',
  '                                )}',
  '                              </div>',
  '                            )}',
  '                          </div>',
  '                          <p className="text-xs text-slate-500">',
  '                            Select multiple symptoms from list or type to add "Other"',
  '                          </p>',
  '                        </div>',
  '                        <div className="flex flex-col gap-1.5">',
  '                          <label htmlFor="gender" className="text-sm font-semibold text-slate-700">',
  '                            Gender <span className="text-red-500">*</span>',
  '                          </label>',
  '                          <select',
  '                            id="gender"',
  '                            name="gender"',
  '                            value={doctorSignupData.gender}',
  '                            onChange={handleDoctorSignupChange}',
  '                            required',
  '                            className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 text-sm text-slate-900 shadow-sm outline-none transition focus:border-[#11496c] focus:outline-none focus:ring-2 focus:ring-[#11496c]/20"',
  '                            style={{ \'--tw-ring-color\': \'rgba(17, 73, 108, 0.2)\' }}',
  '                          >',
  '                            <option value="">Select gender</option>',
  '                            <option value="male">Male</option>',
  '                            <option value="female">Female</option>',
  '                            <option value="other">Other</option>',
  '                            <option value="prefer_not_to_say">Prefer not to say</option>',
  '                          </select>',
  '                        </div>',
  '                        <div className="flex flex-col gap-1.5">',
  '                          <label htmlFor="licenseNumber" className="text-sm font-semibold text-slate-700">',
  '                            License Number <span className="text-red-500">*</span>',
  '                          </label>',
  '                          <div className="relative">',
  '                            <span className="absolute inset-y-0 left-3 flex items-center text-[#11496c]">',
  '                              <IoDocumentTextOutline className="h-5 w-5" aria-hidden="true" />',
  '                            </span>',
  '                            <input',
  '                              id="licenseNumber"',
  '                              name="licenseNumber"',
  '                              type="text"',
  '                              value={doctorSignupData.licenseNumber}',
  '                              onChange={handleDoctorSignupChange}',
  '                              required',
  '                              placeholder="Enter your medical license number"',
  '                              maxLength={50}',
  '                              className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 pl-11 text-sm text-slate-900 shadow-sm outline-none transition focus:border-[#11496c] focus:outline-none focus:ring-2 focus:ring-[#11496c]/20"',
  '                              style={{ \'--tw-ring-color\': \'rgba(17, 73, 108, 0.2)\' }}',
  '                            />',
  '                          </div>',
  '                        </div>',
  ...lines.slice(226)
];

fs.writeFileSync('./src/modules/doctor/doctor-components/login/DoctorSignupForm.jsx', newLines.join('\n'));
console.log('Success');
